[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

; --- 16MB Flash Settings ---
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; --- 8MB PSRAM Settings ---
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=0

; --- FILE SYSTEM SETTING ---
board_build.filesystem = littlefs

; --- Libraries ---
lib_deps =
    knolleary/PubSubClient @ ^2.8