/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_750627_3_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_750627_1[] = { "value" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_750627_2_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
const uint32_t ei_dsp_config_750627_2_axes_size = 10;
ei_dsp_config_raw_t ei_dsp_config_750627_2 = {
    2, // uint32_t blockId
    1, // int implementationVersion
    10, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_750627_2[10] = { 34.462621232347615, 0.009577236382958383, 0.000021584227746642653, 0.6283546603002261, 0.08427038903967947, 15.36185207434193, 1.7068719732534583, 0.6889671868562289, 0.43427103463715866, 26.17777985479999 };
const float ei_dn_standard_scaler_scale_750627_2[10] = { 0.03693177962784986, 132.96057381992952, 1.6744933363077579, 0.3081013298055118, 3.5998041367503166, 0.024346348754090773, 0.21911713937122507, 0.6317992384480047, 0.760505955692883, 0.9354118204889977 };
const float ei_dn_standard_scaler_var_750627_2[10] = { 733.161294040443, 0.00005656583970931026, 0.3566425470889831, 10.53447397133245, 0.0771688905707811, 1687.0669682154785, 20.82798715081868, 2.5051965435734274, 1.7289990755974336, 1.1428633157420225 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_750627_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_750627_2,
    .mean_data_len = 10,
    .scale_data = (float *)ei_dn_standard_scaler_scale_750627_2,
    .scale_data_len = 10,
    .var_data = (float *)ei_dn_standard_scaler_var_750627_2,
    .var_data_len = 10
};
ei_data_normalization_t ei_data_normalization_config_750627_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_750627_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_750627_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_750627_1[ei_dsp_blocks_750627_1_size] = {
    { // DSP block 2
        2,
        10, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_750627_2, // pointer to config struct
        ei_dsp_config_750627_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_750627_2_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_750627_2, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_750627_3 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_750627_3_init,
    .model_invoke = &tflite_learn_750627_3_invoke,
    .model_reset = &tflite_learn_750627_3_reset,
    .model_input = &tflite_learn_750627_3_input,
    .model_output = &tflite_learn_750627_3_output,
};

const uint8_t ei_output_tensors_indices_750627_3[1] = { 0 };
const uint8_t ei_output_tensors_size_750627_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_750627_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_750627_3,
    .output_tensors_size = ei_output_tensors_size_750627_3,
    .quantized = 0,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_750627_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_750627_1_size = 1;
const uint32_t ei_learning_block_750627_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_750627_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_750627_1[ei_learning_blocks_750627_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_750627_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_750627_3_inputs,
        ei_learning_block_750627_3_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_750627_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_750627_1[ei_postprocessing_blocks_750627_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_REGRESSION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_750627_1_size = 0;

uint32_t *freeform_outputs_750627_1 = nullptr;

const ei_impulse_t impulse_750627_1 = {
    .project_id = 750627,
    .project_owner = "nabeelhasan",
    .project_name = "my_project",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 8,

    .nn_input_frame_size = 10,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 10,
    .dsp_input_frame_size = 1 * 10,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_750627_1_size,
    .dsp_blocks = ei_dsp_blocks_750627_1,

    .learning_blocks_size = ei_learning_blocks_750627_1_size,
    .learning_blocks = ei_learning_blocks_750627_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_750627_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_750627_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "speed_kmh + distance_km + acceleration_ms2 + road_elevation_percent + coasting_flag + battery_current_a + energy_con_wh + ke_lost_wh + e_regen_wh + batt_pack_temp_c",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 1,
    .categories = ei_classifier_inferencing_categories_750627_1,
    .results_type = EI_CLASSIFIER_TYPE_REGRESSION,
    .freeform_outputs_size = freeform_outputs_750627_1_size,
    .freeform_outputs = freeform_outputs_750627_1
};

ei_impulse_handle_t impulse_handle_750627_1 = ei_impulse_handle_t( &impulse_750627_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_750627_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_750627_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_750627_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_750627_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
